<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            ['name' => 'Afghanistan', 'isoAlphaCode' => 'AF'],
            ['name' => 'Aland Islands', 'isoAlphaCode' => 'AX'],
            ['name' => 'Albania', 'isoAlphaCode' => 'AL'],
            ['name' => 'Algeria', 'isoAlphaCode' => 'DZ'],
            ['name' => 'American Samoa', 'isoAlphaCode' => 'AS'],
            ['name' => 'Andorra', 'isoAlphaCode' => 'AD'],
            ['name' => 'Angola', 'isoAlphaCode' => 'AO'],
            ['name' => 'Anguilla', 'isoAlphaCode' => 'AI'],
            ['name' => 'Antarctica', 'isoAlphaCode' => 'AQ'],
            ['name' => 'Antigua and Barbuda', 'isoAlphaCode' => 'AG'],
            ['name' => 'Argentina', 'isoAlphaCode' => 'AR'],
            ['name' => 'Armenia', 'isoAlphaCode' => 'AM'],
            ['name' => 'Aruba', 'isoAlphaCode' => 'AW'],
            ['name' => 'Australia', 'isoAlphaCode' => 'AU'],
            ['name' => 'Austria', 'isoAlphaCode' => 'AT'],
            ['name' => 'Azerbaijan', 'isoAlphaCode' => 'AZ'],
            ['name' => 'Bahamas', 'isoAlphaCode' => 'BS'],
            ['name' => 'Bahrain', 'isoAlphaCode' => 'BH'],
            ['name' => 'Bangladesh', 'isoAlphaCode' => 'BD'],
            ['name' => 'Barbados', 'isoAlphaCode' => 'BB'],
            ['name' => 'Belarus', 'isoAlphaCode' => 'BY'],
            ['name' => 'Belgium', 'isoAlphaCode' => 'BE'],
            ['name' => 'Belize', 'isoAlphaCode' => 'BZ'],
            ['name' => 'Benin', 'isoAlphaCode' => 'BJ'],
            ['name' => 'Bermuda', 'isoAlphaCode' => 'BM'],
            ['name' => 'Bhutan', 'isoAlphaCode' => 'BT'],
            ['name' => 'Bolivia', 'isoAlphaCode' => 'BO'],
            ['name' => 'Bonaire, Saint Eustatius and Saba', 'isoAlphaCode' => 'BQ'],
            ['name' => 'Bosnia and Herzegovina', 'isoAlphaCode' => 'BA'],
            ['name' => 'Botswana', 'isoAlphaCode' => 'BW'],
            ['name' => 'Bouvet Island', 'isoAlphaCode' => 'BV'],
            ['name' => 'Brazil', 'isoAlphaCode' => 'BR'],
            ['name' => 'British Indian Ocean Territory', 'isoAlphaCode' => 'IO'],
            ['name' => 'British Virgin Islands', 'isoAlphaCode' => 'VG'],
            ['name' => 'Brunei', 'isoAlphaCode' => 'BN'],
            ['name' => 'Bulgaria', 'isoAlphaCode' => 'BG'],
            ['name' => 'Burkina Faso', 'isoAlphaCode' => 'BF'],
            ['name' => 'Burundi', 'isoAlphaCode' => 'BI'],
            ['name' => 'Cambodia', 'isoAlphaCode' => 'KH'],
            ['name' => 'Cameroon', 'isoAlphaCode' => 'CM'],
            ['name' => 'Canada', 'isoAlphaCode' => 'CA'],
            ['name' => 'Cape Verde', 'isoAlphaCode' => 'CV'],
            ['name' => 'Cayman Islands', 'isoAlphaCode' => 'KY'],
            ['name' => 'Central African Republic', 'isoAlphaCode' => 'CF'],
            ['name' => 'Chad', 'isoAlphaCode' => 'TD'],
            ['name' => 'Chile', 'isoAlphaCode' => 'CL'],
            ['name' => 'China', 'isoAlphaCode' => 'CN'],
            ['name' => 'Christmas Island', 'isoAlphaCode' => 'CX'],
            ['name' => 'Cocos Islands', 'isoAlphaCode' => 'CC'],
            ['name' => 'Colombia', 'isoAlphaCode' => 'CO'],
            ['name' => 'Comoros', 'isoAlphaCode' => 'KM'],
            ['name' => 'Cook Islands', 'isoAlphaCode' => 'CK'],
            ['name' => 'Costa Rica', 'isoAlphaCode' => 'CR'],
            ['name' => 'Croatia', 'isoAlphaCode' => 'HR'],
            ['name' => 'Cuba', 'isoAlphaCode' => 'CU'],
            ['name' => 'Curacao', 'isoAlphaCode' => 'CW'],
            ['name' => 'Cyprus', 'isoAlphaCode' => 'CY'],
            ['name' => 'Czech Republic', 'isoAlphaCode' => 'CZ'],
            ['name' => 'Democratic Republic of the Congo', 'isoAlphaCode' => 'CD'],
            ['name' => 'Denmark', 'isoAlphaCode' => 'DK'],
            ['name' => 'Djibouti', 'isoAlphaCode' => 'DJ'],
            ['name' => 'Dominica', 'isoAlphaCode' => 'DM'],
            ['name' => 'Dominican Republic', 'isoAlphaCode' => 'DO'],
            ['name' => 'East Timor', 'isoAlphaCode' => 'TL'],
            ['name' => 'Ecuador', 'isoAlphaCode' => 'EC'],
            ['name' => 'Egypt', 'isoAlphaCode' => 'EG'],
            ['name' => 'El Salvador', 'isoAlphaCode' => 'SV'],
            ['name' => 'Equatorial Guinea', 'isoAlphaCode' => 'GQ'],
            ['name' => 'Eritrea', 'isoAlphaCode' => 'ER'],
            ['name' => 'Estonia', 'isoAlphaCode' => 'EE'],
            ['name' => 'Ethiopia', 'isoAlphaCode' => 'ET'],
            ['name' => 'Falkland Islands', 'isoAlphaCode' => 'FK'],
            ['name' => 'Faroe Islands', 'isoAlphaCode' => 'FO'],
            ['name' => 'Fiji', 'isoAlphaCode' => 'FJ'],
            ['name' => 'Finland', 'isoAlphaCode' => 'FI'],
            ['name' => 'France', 'isoAlphaCode' => 'FR'],
            ['name' => 'French Guiana', 'isoAlphaCode' => 'GF'],
            ['name' => 'French Polynesia', 'isoAlphaCode' => 'PF'],
            ['name' => 'French Southern Territories', 'isoAlphaCode' => 'TF'],
            ['name' => 'Gabon', 'isoAlphaCode' => 'GA'],
            ['name' => 'Gambia', 'isoAlphaCode' => 'GM'],
            ['name' => 'Georgia', 'isoAlphaCode' => 'GE'],
            ['name' => 'Germany', 'isoAlphaCode' => 'DE'],
            ['name' => 'Ghana', 'isoAlphaCode' => 'GH'],
            ['name' => 'Gibraltar', 'isoAlphaCode' => 'GI'],
            ['name' => 'Greece', 'isoAlphaCode' => 'GR'],
            ['name' => 'Greenland', 'isoAlphaCode' => 'GL'],
            ['name' => 'Grenada', 'isoAlphaCode' => 'GD'],
            ['name' => 'Guadeloupe', 'isoAlphaCode' => 'GP'],
            ['name' => 'Guam', 'isoAlphaCode' => 'GU'],
            ['name' => 'Guatemala', 'isoAlphaCode' => 'GT'],
            ['name' => 'Guernsey', 'isoAlphaCode' => 'GG'],
            ['name' => 'Guinea', 'isoAlphaCode' => 'GN'],
            ['name' => 'Guinea-Bissau', 'isoAlphaCode' => 'GW'],
            ['name' => 'Guyana', 'isoAlphaCode' => 'GY'],
            ['name' => 'Haiti', 'isoAlphaCode' => 'HT'],
            ['name' => 'Heard Island and McDonald Islands', 'isoAlphaCode' => 'HM'],
            ['name' => 'Honduras', 'isoAlphaCode' => 'HN'],
            ['name' => 'Hong Kong', 'isoAlphaCode' => 'HK'],
            ['name' => 'Hungary', 'isoAlphaCode' => 'HU'],
            ['name' => 'Iceland', 'isoAlphaCode' => 'IS'],
            ['name' => 'India', 'isoAlphaCode' => 'IN'],
            ['name' => 'Indonesia', 'isoAlphaCode' => 'ID'],
            ['name' => 'Iran', 'isoAlphaCode' => 'IR'],
            ['name' => 'Iraq', 'isoAlphaCode' => 'IQ'],
            ['name' => 'Ireland', 'isoAlphaCode' => 'IE'],
            ['name' => 'Isle of Man', 'isoAlphaCode' => 'IM'],
            ['name' => 'Israel', 'isoAlphaCode' => 'IL'],
            ['name' => 'Italy', 'isoAlphaCode' => 'IT'],
            ['name' => 'Ivory Coast', 'isoAlphaCode' => 'CI'],
            ['name' => 'Jamaica', 'isoAlphaCode' => 'JM'],
            ['name' => 'Japan', 'isoAlphaCode' => 'JP'],
            ['name' => 'Jersey', 'isoAlphaCode' => 'JE'],
            ['name' => 'Jordan', 'isoAlphaCode' => 'JO'],
            ['name' => 'Kazakhstan', 'isoAlphaCode' => 'KZ'],
            ['name' => 'Kenya', 'isoAlphaCode' => 'KE'],
            ['name' => 'Kiribati', 'isoAlphaCode' => 'KI'],
            ['name' => 'Kosovo', 'isoAlphaCode' => 'XK'],
            ['name' => 'Kuwait', 'isoAlphaCode' => 'KW'],
            ['name' => 'Kyrgyzstan', 'isoAlphaCode' => 'KG'],
            ['name' => 'Laos', 'isoAlphaCode' => 'LA'],
            ['name' => 'Latvia', 'isoAlphaCode' => 'LV'],
            ['name' => 'Lebanon', 'isoAlphaCode' => 'LB'],
            ['name' => 'Lesotho', 'isoAlphaCode' => 'LS'],
            ['name' => 'Liberia', 'isoAlphaCode' => 'LR'],
            ['name' => 'Libya', 'isoAlphaCode' => 'LY'],
            ['name' => 'Liechtenstein', 'isoAlphaCode' => 'LI'],
            ['name' => 'Lithuania', 'isoAlphaCode' => 'LT'],
            ['name' => 'Luxembourg', 'isoAlphaCode' => 'LU'],
            ['name' => 'Macao', 'isoAlphaCode' => 'MO'],
            ['name' => 'Macedonia', 'isoAlphaCode' => 'MK'],
            ['name' => 'Madagascar', 'isoAlphaCode' => 'MG'],
            ['name' => 'Malawi', 'isoAlphaCode' => 'MW'],
            ['name' => 'Malaysia', 'isoAlphaCode' => 'MY'],
            ['name' => 'Maldives', 'isoAlphaCode' => 'MV'],
            ['name' => 'Mali', 'isoAlphaCode' => 'ML'],
            ['name' => 'Malta', 'isoAlphaCode' => 'MT'],
            ['name' => 'Marshall Islands', 'isoAlphaCode' => 'MH'],
            ['name' => 'Martinique', 'isoAlphaCode' => 'MQ'],
            ['name' => 'Mauritania', 'isoAlphaCode' => 'MR'],
            ['name' => 'Mauritius', 'isoAlphaCode' => 'MU'],
            ['name' => 'Mayotte', 'isoAlphaCode' => 'YT'],
            ['name' => 'Mexico', 'isoAlphaCode' => 'MX'],
            ['name' => 'Micronesia', 'isoAlphaCode' => 'FM'],
            ['name' => 'Moldova', 'isoAlphaCode' => 'MD'],
            ['name' => 'Monaco', 'isoAlphaCode' => 'MC'],
            ['name' => 'Mongolia', 'isoAlphaCode' => 'MN'],
            ['name' => 'Montenegro', 'isoAlphaCode' => 'ME'],
            ['name' => 'Montserrat', 'isoAlphaCode' => 'MS'],
            ['name' => 'Morocco', 'isoAlphaCode' => 'MA'],
            ['name' => 'Mozambique', 'isoAlphaCode' => 'MZ'],
            ['name' => 'Myanmar', 'isoAlphaCode' => 'MM'],
            ['name' => 'Namibia', 'isoAlphaCode' => 'NA'],
            ['name' => 'Nauru', 'isoAlphaCode' => 'NR'],
            ['name' => 'Nepal', 'isoAlphaCode' => 'NP'],
            ['name' => 'Netherlands', 'isoAlphaCode' => 'NL'],
            ['name' => 'New Caledonia', 'isoAlphaCode' => 'NC'],
            ['name' => 'New Zealand', 'isoAlphaCode' => 'NZ'],
            ['name' => 'Nicaragua', 'isoAlphaCode' => 'NI'],
            ['name' => 'Niger', 'isoAlphaCode' => 'NE'],
            ['name' => 'Nigeria', 'isoAlphaCode' => 'NG'],
            ['name' => 'Niue', 'isoAlphaCode' => 'NU'],
            ['name' => 'Norfolk Island', 'isoAlphaCode' => 'NF'],
            ['name' => 'North Korea', 'isoAlphaCode' => 'KP'],
            ['name' => 'Northern Mariana Islands', 'isoAlphaCode' => 'MP'],
            ['name' => 'Norway', 'isoAlphaCode' => 'NO'],
            ['name' => 'Oman', 'isoAlphaCode' => 'OM'],
            ['name' => 'Pakistan', 'isoAlphaCode' => 'PK'],
            ['name' => 'Palau', 'isoAlphaCode' => 'PW'],
            ['name' => 'Palestinian Territory', 'isoAlphaCode' => 'PS'],
            ['name' => 'Panama', 'isoAlphaCode' => 'PA'],
            ['name' => 'Papua New Guinea', 'isoAlphaCode' => 'PG'],
            ['name' => 'Paraguay', 'isoAlphaCode' => 'PY'],
            ['name' => 'Peru', 'isoAlphaCode' => 'PE'],
            ['name' => 'Philippines', 'isoAlphaCode' => 'PH'],
            ['name' => 'Pitcairn', 'isoAlphaCode' => 'PN'],
            ['name' => 'Poland', 'isoAlphaCode' => 'PL'],
            ['name' => 'Portugal', 'isoAlphaCode' => 'PT'],
            ['name' => 'Puerto Rico', 'isoAlphaCode' => 'PR'],
            ['name' => 'Qatar', 'isoAlphaCode' => 'QA'],
            ['name' => 'Republic of the Congo', 'isoAlphaCode' => 'CG'],
            ['name' => 'Reunion', 'isoAlphaCode' => 'RE'],
            ['name' => 'Romania', 'isoAlphaCode' => 'RO'],
            ['name' => 'Russia', 'isoAlphaCode' => 'RU'],
            ['name' => 'Rwanda', 'isoAlphaCode' => 'RW'],
            ['name' => 'Saint Barthelemy', 'isoAlphaCode' => 'BL'],
            ['name' => 'Saint Helena', 'isoAlphaCode' => 'SH'],
            ['name' => 'Saint Kitts and Nevis', 'isoAlphaCode' => 'KN'],
            ['name' => 'Saint Lucia', 'isoAlphaCode' => 'LC'],
            ['name' => 'Saint Martin', 'isoAlphaCode' => 'MF'],
            ['name' => 'Saint Pierre and Miquelon', 'isoAlphaCode' => 'PM'],
            ['name' => 'Saint Vincent and the Grenadines', 'isoAlphaCode' => 'VC'],
            ['name' => 'Samoa', 'isoAlphaCode' => 'WS'],
            ['name' => 'San Marino', 'isoAlphaCode' => 'SM'],
            ['name' => 'Sao Tome and Principe', 'isoAlphaCode' => 'ST'],
            ['name' => 'Saudi Arabia', 'isoAlphaCode' => 'SA'],
            ['name' => 'Senegal', 'isoAlphaCode' => 'SN'],
            ['name' => 'Serbia', 'isoAlphaCode' => 'RS'],
            ['name' => 'Seychelles', 'isoAlphaCode' => 'SC'],
            ['name' => 'Sierra Leone', 'isoAlphaCode' => 'SL'],
            ['name' => 'Singapore', 'isoAlphaCode' => 'SG'],
            ['name' => 'Sint Maarten', 'isoAlphaCode' => 'SX'],
            ['name' => 'Slovakia', 'isoAlphaCode' => 'SK'],
            ['name' => 'Slovenia', 'isoAlphaCode' => 'SI'],
            ['name' => 'Solomon Islands', 'isoAlphaCode' => 'SB'],
            ['name' => 'Somalia', 'isoAlphaCode' => 'SO'],
            ['name' => 'South Africa', 'isoAlphaCode' => 'ZA'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'isoAlphaCode' => 'GS'],
            ['name' => 'South Korea', 'isoAlphaCode' => 'KR'],
            ['name' => 'South Sudan', 'isoAlphaCode' => 'SS'],
            ['name' => 'Spain', 'isoAlphaCode' => 'ES'],
            ['name' => 'Sri Lanka', 'isoAlphaCode' => 'LK'],
            ['name' => 'Sudan', 'isoAlphaCode' => 'SD'],
            ['name' => 'Suriname', 'isoAlphaCode' => 'SR'],
            ['name' => 'Svalbard and Jan Mayen', 'isoAlphaCode' => 'SJ'],
            ['name' => 'Swaziland', 'isoAlphaCode' => 'SZ'],
            ['name' => 'Sweden', 'isoAlphaCode' => 'SE'],
            ['name' => 'Switzerland', 'isoAlphaCode' => 'CH'],
            ['name' => 'Syria', 'isoAlphaCode' => 'SY'],
            ['name' => 'Taiwan', 'isoAlphaCode' => 'TW'],
            ['name' => 'Tajikistan', 'isoAlphaCode' => 'TJ'],
            ['name' => 'Tanzania', 'isoAlphaCode' => 'TZ'],
            ['name' => 'Thailand', 'isoAlphaCode' => 'TH'],
            ['name' => 'Togo', 'isoAlphaCode' => 'TG'],
            ['name' => 'Tokelau', 'isoAlphaCode' => 'TK'],
            ['name' => 'Tonga', 'isoAlphaCode' => 'TO'],
            ['name' => 'Trinidad and Tobago', 'isoAlphaCode' => 'TT'],
            ['name' => 'Tunisia', 'isoAlphaCode' => 'TN'],
            ['name' => 'Turkey', 'isoAlphaCode' => 'TR'],
            ['name' => 'Turkmenistan', 'isoAlphaCode' => 'TM'],
            ['name' => 'Turks and Caicos Islands', 'isoAlphaCode' => 'TC'],
            ['name' => 'Tuvalu', 'isoAlphaCode' => 'TV'],
            ['name' => 'U.S. Virgin Islands', 'isoAlphaCode' => 'VI'],
            ['name' => 'Uganda', 'isoAlphaCode' => 'UG'],
            ['name' => 'Ukraine', 'isoAlphaCode' => 'UA'],
            ['name' => 'United Arab Emirates', 'isoAlphaCode' => 'AE'],
            ['name' => 'United Kingdom', 'isoAlphaCode' => 'GB'],
            ['name' => 'United States', 'isoAlphaCode' => 'US'],
            ['name' => 'United States Minor Outlying Islands', 'isoAlphaCode' => 'UM'],
            ['name' => 'Uruguay', 'isoAlphaCode' => 'UY'],
            ['name' => 'Uzbekistan', 'isoAlphaCode' => 'UZ'],
            ['name' => 'Vanuatu', 'isoAlphaCode' => 'VU'],
            ['name' => 'Vatican', 'isoAlphaCode' => 'VA'],
            ['name' => 'Venezuela', 'isoAlphaCode' => 'VE'],
            ['name' => 'Vietnam', 'isoAlphaCode' => 'VN'],
            ['name' => 'Wallis and Futuna', 'isoAlphaCode' => 'WF'],
            ['name' => 'Western Sahara', 'isoAlphaCode' => 'EH'],
            ['name' => 'Yemen', 'isoAlphaCode' => 'YE'],
            ['name' => 'Zambia', 'isoAlphaCode' => 'ZM'],
            ['name' => 'Zimbabwe', 'isoAlphaCode' => 'ZW'],
        );

        DB::table('countries')->insert($countries);
    }
}